### ISSUE TITLE
Various issues after adding 2nd Algorand account on Ledger Nano S

### ISSUE THREAD

**Issue by cccassidy** [algorand/ledger-app-algorand#58] opened 2022-01-30 16:41 UTC
### Subject of the issue

A few weeks back I added a 2nd Algo account to my Ledger Nano S for use with Tinyman as I wanted to keep an account separate for Governance purposes.  While the account initially added fine on Ledger Live I started running into issues trying to sign transactions after I opted into the Yieldly ASA.  In an attempt to restore the system I did a full remove/add on Algorand in Ledger Live which caused further issues.  I am now unable to make any transactions with Algo on the 2nd account either with Ledger Live or the Algosigner extension.  Ledger Live throws a decode error upon signing and the Algosigner app never even triggers a signature request on the device.

Since there are issues across multiple Algo front end applications I wanted to raise a ticket here in case something comes back to the Ledger device app itself.

Related tickets:
https://github.com/PureStake/algosigner/issues/350
https://github.com/LedgerHQ/ledger-live-desktop/issues/4226

### Your environment

Windows 10 (also same issue with Ubuntu VirtualBox VM)
Algosigner 1.17.2
LedgerLive 2.37.2
Ledger Algorand App 1.2.15
Ledger Nano S w/ 2.1.0 firmware

### Steps to reproduce

1. Added 2nd algo account to Ledger Nano S
2. Opted into Tinyman + Yieldly ASA on 2nd account with AlgoSigner
3. After the Yieldly ASA opt-in everything seemed to stop working

### Expected behaviour

Able to sign transactions w/ AlgoSigner and/or Ledger Live

### Actual behaviour

Transaction never makes it to the Ledger device w/ AlgoSigner, Legder Live various errors once 2nd account is added in.

**Comment by rotemh** [comment] 2022-10-03 20:09
Hi @cccassidy,

Thanks for the issue. AlgoSigner or TinyMan are not part of our product suite, and unfortunately, we can't help with that. 
Since the issue is being handled at the other threads, I'm closing the issue. Please open a new one if there is any issue with the Algorand Ledger app. 

Best,

**Closed by rotemh** 2022-10-03 20:09 UTC
Labels: new-bug
